version: 1
articles:
- slug: project
  title: About This Project
  visibility:
    min_stage: OK
    include_in_nav: true
    pin_to_top: true
  meta:
    description: What Continuity Orchestrator is, how it works, and why it exists
    author: System
    tags:
    - info
    - overview
- slug: about
  title: How It Works
  visibility:
    min_stage: OK
    include_in_nav: true
    pin_to_top: false
  meta:
    description: Project overview and objectives
    author: System
    tags:
    - info
- slug: full_disclosure
  title: Full Disclosure Statement
  visibility:
    min_stage: FULL
    include_in_nav: true
    pin_to_top: false
  meta:
    description: Template disclosure document
    author: System
    tags:
    - disclosure
defaults:
  visibility:
    min_stage: FULL
    include_in_nav: false
stages:
  OK:
    show_countdown: false
  REMIND_1:
    banner: "\u23F0 Reminder: Deadline approaching"
    banner_class: warning
    show_countdown: true
  REMIND_2:
    banner: "\u26A0\uFE0F Final warning: Action required"
    banner_class: warning
    show_countdown: true
  PRE_RELEASE:
    banner: "\U0001F534 Pre-release mode active"
    banner_class: alert
    show_countdown: true
  PARTIAL:
    banner: "\U0001F4E2 Partial disclosure in effect"
    banner_class: critical
    show_countdown: true
  FULL:
    banner: "\U0001F6A8 Full disclosure mode"
    banner_class: critical
    show_countdown: false
